name: Deploying to Staging

on:
  push:
    branches:
      - main

jobs:

 
  deploy:
    name: Deploy to Server
    runs-on: [self-hosted, backend]

    steps:
      - name: Deploy with Docker Compose
        run: |
          cd /home/raoua/devops-script/backend
          docker compose pull backend-api
          docker compose up -d backend-api --force-recreate