name: Deploying to Staging

on:
    push:
      branches:
        - main

jobs:
    test:
        runs-on:
            - ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: install dependencies
              run: npm install
            - name: run tests
              run: npm test

    deploy-and-push:
        needs: test
        runs-on:
            - ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: build docker image 
              run: docker build -t raouamth/backend-session16 .
            - name: push docker image to docker hub
              uses: docker/login-action@v3
              with:
                username: ${{ vars.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
            - name: push image to docker hub
              run: docker push raouamth/backend-session16    
